name: llps_predictor
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip=22.3.1
  - pip:
      - fair-esm==2.0.0
      - numpy==1.24.3
      - pandas==2.2.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - tensorflow==2.19.0
      - torch==2.7.0
      - tqdm==4.67.1
